spring.application.name=sfas-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sfas
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

# JWT Configuration
jwt.secret=v9y/B?E(H+MbQeThWmZq4t7w!z%C&F)J@KaPdSgVkYp3s6v9
